# @format

name: Sync GitLab Contributions

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch GitLab Contributions
        env:
          GITLAB_ACCESS_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
        run: |
          curl --header "PRIVATE-TOKEN: $GITLAB_ACCESS_TOKEN" https://gitlab.lanexus.com/api/v4/events?scope=all > gitlab_contributions.json
          cat gitlab_contributions.json

      - name: Process and Update Contributions
        run: |
          # You can add your own logic here to process and update your GitHub profile with the fetched data.
          # For example, parse the JSON and update a README file in your repository.
          echo "Contributions fetched and processed"
